export type Plugins = {
    bootstrapTooltip: NodeListOf<HTMLElement>;
    bootstrapModalDialog: NodeListOf<HTMLElement>;
    bootstrapTabs: NodeListOf<HTMLElement>;
    rdNavbar: NodeListOf<HTMLElement>;
    materialParallax: NodeListOf<HTMLElement>;
    rdGoogleMaps: NodeListOf<HTMLElement>;
    rdMailForm: NodeListOf<HTMLElement>;
    rdInputLabel: NodeListOf<HTMLElement>;
    regula: NodeListOf<HTMLElement>;
    wow: NodeListOf<HTMLElement>;
    owl: NodeListOf<HTMLElement>;
    swiper: NodeListOf<HTMLElement>;
    search: NodeListOf<HTMLElement>;
    searchResults: NodeListOf<HTMLElement>;
    statefulButton: NodeListOf<HTMLElement>;
    isotope: NodeListOf<HTMLElement>;
    popover: NodeListOf<HTMLElement>;
    viewAnimate: NodeListOf<HTMLElement>;
    radio: NodeListOf<HTMLInputElement>;
    checkbox: NodeListOf<HTMLInputElement>;
    customToggle: NodeListOf<HTMLElement>;
    counter: NodeListOf<HTMLElement>;
    preloader: NodeListOf<HTMLElement>;
    captcha: NodeListOf<HTMLElement>;
    lightGallery: NodeListOf<HTMLElement>;
    lightGalleryItem: NodeListOf<HTMLElement>;
    lightDynamicGalleryItem: NodeListOf<HTMLElement>;
    mailchimp: NodeListOf<HTMLElement>;
    campaignMonitor: NodeListOf<HTMLElement>;
    copyrightYear: NodeListOf<HTMLElement>;
    buttonWinona: NodeListOf<HTMLElement>;
    slick: NodeListOf<HTMLElement>;
    videoOverlay: NodeListOf<HTMLElement>;
    d3Charts: NodeListOf<HTMLElement>;
    selectFilter: NodeListOf<HTMLElement>;
    maps: NodeListOf<HTMLElement>;
    hoverdir: NodeListOf<HTMLElement>;
    vide: NodeListOf<HTMLElement>;
    progressLinear: NodeListOf<HTMLElement>;
    countdown: NodeListOf<HTMLElement>;
    lazyComponent: HTMLElement | Element | null
};
const a = document.querySelector('.lazy-component')